package com.chachae.exam.vault;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.annotation.PostConstruct;

@Component
public class VaultSchema {

  private final JdbcTemplate jdbcTemplate;

  public VaultSchema(JdbcTemplate jdbcTemplate) {
    this.jdbcTemplate = jdbcTemplate;
  }

  @PostConstruct
  public void initialize() {
    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_papers ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "title VARCHAR(255) NOT NULL,"
            + "exam_type VARCHAR(50),"
            + "province VARCHAR(50),"
            + "year INT,"
            + "subject VARCHAR(50),"
            + "duration_seconds INT DEFAULT 7200,"
            + "total_questions INT DEFAULT 0,"
            + "source VARCHAR(255),"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_passages ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "paper_id BIGINT,"
            + "title VARCHAR(255),"
            + "content CLOB,"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_questions ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "paper_id BIGINT,"
            + "passage_id BIGINT,"
            + "number INT,"
            + "exam_type VARCHAR(50),"
            + "province VARCHAR(50),"
            + "year INT,"
            + "subject VARCHAR(50),"
            + "module VARCHAR(50),"
            + "question_type VARCHAR(100),"
            + "stem CLOB NOT NULL,"
            + "options_json CLOB,"
            + "answer VARCHAR(20),"
            + "explanation CLOB,"
            + "score DOUBLE DEFAULT 1,"
            + "tags_json CLOB,"
            + "source VARCHAR(255),"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_import_jobs ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "file_name VARCHAR(255),"
            + "source_type VARCHAR(50),"
            + "raw_text CLOB,"
            + "status VARCHAR(50) DEFAULT 'parsed',"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_import_candidates ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "import_job_id BIGINT,"
            + "paper_title VARCHAR(255),"
            + "number INT,"
            + "exam_type VARCHAR(50),"
            + "province VARCHAR(50),"
            + "year INT,"
            + "subject VARCHAR(50),"
            + "module VARCHAR(50),"
            + "question_type VARCHAR(100),"
            + "passage_text CLOB,"
            + "stem CLOB,"
            + "options_json CLOB,"
            + "answer VARCHAR(20),"
            + "explanation CLOB,"
            + "score DOUBLE DEFAULT 1,"
            + "tags_json CLOB,"
            + "source VARCHAR(255),"
            + "status VARCHAR(50) DEFAULT 'pending',"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_exam_sessions ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "paper_id BIGINT,"
            + "mode VARCHAR(50) NOT NULL,"
            + "title VARCHAR(255) NOT NULL,"
            + "duration_seconds INT DEFAULT 7200,"
            + "started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "submitted_at TIMESTAMP,"
            + "total_questions INT DEFAULT 0,"
            + "answered_count INT DEFAULT 0,"
            + "correct_count INT DEFAULT 0,"
            + "wrong_count INT DEFAULT 0,"
            + "score DOUBLE DEFAULT 0,"
            + "accuracy DOUBLE DEFAULT 0,"
            + "status VARCHAR(50) DEFAULT 'ongoing',"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE TABLE IF NOT EXISTS vault_answer_records ("
            + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "exam_session_id BIGINT NOT NULL,"
            + "question_id BIGINT NOT NULL,"
            + "question_order INT NOT NULL,"
            + "user_answer VARCHAR(20),"
            + "correct_answer VARCHAR(20),"
            + "is_correct BOOLEAN DEFAULT FALSE,"
            + "time_spent_seconds INT DEFAULT 0,"
            + "first_enter_at TIMESTAMP,"
            + "last_leave_at TIMESTAMP,"
            + "changed_times INT DEFAULT 0,"
            + "marked_for_review BOOLEAN DEFAULT FALSE,"
            + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,"
            + "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP"
            + ")");

    jdbcTemplate.execute(
        "CREATE INDEX IF NOT EXISTS idx_vault_questions_filters "
            + "ON vault_questions(exam_type, province, year, subject, module)");
    jdbcTemplate.execute(
        "CREATE INDEX IF NOT EXISTS idx_vault_records_session "
            + "ON vault_answer_records(exam_session_id, question_order)");
  }
}
